import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { NextIntlClientProvider } from "next-intl";
import Contact from "./contact/Contact";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { locales } from "@/config";
import { ThemeProvider } from "@/components/theme-provider.tsx";

export const metadata: Metadata = {
  title: "Khiari Haifa",
  description: "Generated by Khiari Haifa",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!locales.includes(params.locale as any)) {
    notFound();
  }
  const messages = await getMessages({ locale: params.locale });
  return (
    <html lang={params.locale} suppressHydrationWarning>
      <body className="bg-gradient-to-br from-[#9A33FF]/5 to-[#FF8660]/5 dark:bg-black">
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Contact />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
