import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { NextIntlClientProvider } from "next-intl";
import Contact from "./contact/Contact";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { locales } from "@/config";

export const metadata: Metadata = {
  title: "Khiari Haifa",
  description: "Generated by Khiari Haifa",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!locales.includes(params.locale as any)) {
    notFound();
  }
  const messages = await getMessages({ locale: params.locale });
  return (
    <html lang={params.locale}>
      <body className=" bg-black">
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
          <Contact />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
